image: docker:latest

variables:
  DOCKER_DRIVER: overlay

stages:
  - test
  - build
  - package
  - deploy

npm-test:
  image: node:alpine
  stage: test
  script:
    - cd client
    - npm i
    - cd ..
    - npm i
    - npm test

npm-build:
  image: node:alpine
  stage: build
  script:
    - npm i
    - npm run build
    - cd client
    - npm i
    - npm run build
  artifacts:
    paths:
      - client/public/*
      - server.js

docker-build:
  stage: package
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}
    - docker build -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" .
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" "${CI_REGISTRY_IMAGE}:latest"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
    - docker push "${CI_REGISTRY_IMAGE}:latest"
  only:
    - master

deploy-dev:
  stage: deploy
  image:
    name: quay.io/ukhomeofficedigital/kd:latest
    entrypoint: ["/bin/bash", "-c"]
  script:
    - echo "${KUBE_SERVER}"
    - KUBE_NAMESPACE=harmelodic INGRESS_HOST=scribbles.harmelodic.com IMAGE_TAG="${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" APP_NAME=scribbles kd --insecure-skip-tls-verify --timeout=5m0s -f ${CI_PROJECT_DIR}/k8s
  only:
    - master