apiVersion: v1
kind: ConfigMap
metadata:
  name: mail
  namespace: {{.KUBE_NAMESPACE}}
data:
  server: {{.MAIL_SERVER}}
  username: {{.MAIL_USERNAME}}
  password: {{.MAIL_PASSWORD}}
  target: {{.MAIL_TARGET}}