apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{.APP_NAME}}
  namespace: {{.KUBE_NAMESPACE}}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: {{.APP_NAME}}
        env: {{.KUBE_NAMESPACE}}
    spec:
      containers:
      - name: {{.APP_NAME}}
        image: "{{.IMAGE_TAG}}"
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: PORT
            value: "80"
          - name: MAIL_SERVER
            valueFrom:
              configMapKeyRef:
                name: mail
                key: server
          - name: MAIL_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mail
                key: username
          - name: MAIL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mail
                key: password
          - name: MAIL_TARGET
            valueFrom:
              configMapKeyRef:
                name: mail
                key: target
        resources:
          requests:
            memory: "0.05Gi"
            cpu: "0.008"
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 60
          httpGet:
            port: 80
            path: /
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        command: ["/cloud_sql_proxy",
                  "-instances=harm-personal-projects:europe-west2:prod-mysql=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: shopping-cloudsql-proxy
            mountPath: /secrets/cloudsql
            readOnly: true
      imagePullSecrets:
      - name: {{.APP_NAME}}-registry-deploy-token
      volumes:
        - name: shopping-cloudsql-proxy
          secret:
            secretName: shopping-cloudsql-proxy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0