apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: shopping
  app.kubernetes.io/part-of: shopping
resources:
  - config-map.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
